### ISSUE TITLE
Error: Problem in packages configuration file: Unrecognized string escape

### ISSUE THREAD

**Issue by JsonYuu** [alibaba-flutter/aspectd#101]
![image](https://user-images.githubusercontent.com/20380136/110410972-b72c2100-80c4-11eb-9894-ba654f1546d6.png)

`C:\AndroidStudio\flutter_sdk\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\AndroidStudio\flutter_sdk\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --no-link-platform --packages C:\gittest\aspectd\example\.packages --output-dill
C:\gittest\aspectd\example\.dart_tool\flutter_build\6fc2de4a5ec238ac0b441454eaa8d3da\app.dill --depfile
C:\gittest\aspectd\example\.dart_tool\flutter_build\6fc2de4a5ec238ac0b441454eaa8d3da\kernel_snapshot.d package:example/main.dart
[+10296 ms] [+10230 ms] Persisting file store
[   +1 ms] [   +4 ms] Done persisting file store
[   +4 ms] [   +5 ms] Target kernel_snapshot failed: Exception: Aspectd unexpected error: ../lib/src/flutter_frontend_server/rebased_package_config.json:
Error: Problem in packages configuration file: Unrecognized string escape
[   +5 ms]            Error: Could not resolve the package 'args' in 'package:args/args.dart'.
[        ]            Error: Could not resolve the package 'frontend_server' in 'package:frontend_server/frontend_server.dart'.
[   +1 ms]            Error: Could not resolve the package 'kernel' in 'package:kernel/ast.dart'.
[   +1 ms]            Error: Could not resolve the package 'path' in 'package:path/path.dart'.
[        ]            Error: Could not resolve the package 'vm' in 'package:vm/incremental_compiler.dart'.
[        ]            Error: Could not resolve the package 'vm' in 'package:vm/target/flutter.dart'.
[        ]            ../lib/src/flutter_frontend_server/server.dart:10:8: Error: Not found: 'package:args/args.dart'
[   +1 ms]            import 'package:args/args.dart';
[   +1 ms]                   ^
[   +1 ms]            ../lib/src/flutter_frontend_server/server.dart:11:8: Error: Not found: 'package:frontend_server/frontend_server.dart'
[   +1 ms]            import 'package:frontend_server/frontend_server.dart' as frontend
[   +1 ms]                   ^
[   +1 ms]            ../lib/src/flutter_frontend_server/server.dart:19:8: Error: Not found: 'package:kernel/ast.dart'
[   +1 ms]            import 'package:kernel/ast.dart';
[   +1 ms]                   ^
[   +2 ms]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[   +1 ms]            #1      AspectdHook.checkAspectdFlutterFrontendServerSnapshot (package:flutter_tools/src/aspectd.dart:128:9)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #2      AspectdHook.isAspectdEnabled (package:flutter_tools/src/aspectd.dart:82:18)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #3      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:198:27)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #4      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
[   +1 ms]            #5      _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +1 ms]            #7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +1 ms]            #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +2 ms]            #9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +1 ms]            #10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +1 ms]            #11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[   +1 ms]            #12     _rootRun (dart:async/zone.dart:1190:13)
[   +3 ms]            #13     _CustomZone.run (dart:async/zone.dart:1093:19)
[   +2 ms]            #14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[   +1 ms]            #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[   +4 ms]            #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[   +1 ms]            #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[   +1 ms]            #18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[   +1 ms]            #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[   +1 ms] [   +5 ms] 
[   +1 ms]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[   +2 ms]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:238:7)
[   +1 ms]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +1 ms]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +1 ms]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +3 ms]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +5 ms]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +1 ms]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +1 ms]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[   +1 ms]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[   +1 ms]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +2 ms]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +1 ms]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[   +3 ms] [  +13 ms] "flutter assemble" took 10,460ms.
[   +7 ms]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +1 ms]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +1 ms]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +2 ms]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[   +1 ms]            #35     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[   +1 ms]            #36     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ]            #37     _rootRunBinary (dart:async/zone.dart:1214:47)
[   +1 ms]            #38     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[   +1 ms]            #39     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[   +1 ms]            #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[   +1 ms]            #41     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[   +2 ms]            #42     Future._completeError (dart:async/future_impl.dart:537:5)
[   +2 ms]            #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[   +2 ms]            #44     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart)
[   +2 ms]            #45     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[   +1 ms]            #46     _rootRunBinary (dart:async/zone.dart:1214:47)
[   +1 ms]            #47     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[   +1 ms]            #48     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[   +1 ms]            #49     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[   +1 ms]            #50     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[   +1 ms]            #51     Future._completeError (dart:async/future_impl.dart:537:5)
[   +1 ms]            #52     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[   +2 ms]            #53     AspectdHook.isAspectdEnabled (package:flutter_tools/src/aspectd.dart)
[   +1 ms]            #54     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[   +1 ms]            #55     _rootRunBinary (dart:async/zone.dart:1214:47)
[   +1 ms]            #56     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[   +1 ms]            #57     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[   +2 ms]            #58     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[   +1 ms]            #59     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[   +1 ms]            #60     Future._completeError (dart:async/future_impl.dart:537:5)
[   +2 ms]            #61     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[   +1 ms]            #62     AspectdHook.checkAspectdFlutterFrontendServerSnapshot (package:flutter_tools/src/aspectd.dart)
[   +1 ms]            #63     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +2 ms]            #64     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +1 ms]            #65     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +2 ms]            #66     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #67     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #68     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #69     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #70     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #71     _run (package:flutter_tools/src/base/error_handling_io.dart)
[   +1 ms]            #72     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #73     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #74     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #75     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +1 ms]            #76     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +1 ms]            #77     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +1 ms]            #78     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[   +4 ms]            #79     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #80     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +1 ms]            #81     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +1 ms]            #82     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +1 ms]            #83     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +1 ms]            #84     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +2 ms]            #85     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[   +2 ms]            #86     _rootRun (dart:async/zone.dart:1190:13)
[   +1 ms]            #87     _CustomZone.run (dart:async/zone.dart:1093:19)
[   +1 ms]            #88     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[   +2 ms] [   +3 ms] ensureAnalyticsSent: 0ms
[   +1 ms] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[   +1 ms] [        ] exiting with code 1
[   +1 ms] > Task :app:compileFlutterBuildDebug FAILED
[   +1 ms] 1 actionable task: 1 executed
[   +1 ms]            #89     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[   +1 ms]            #90     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[   +1 ms]            #91     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[   +4 ms]            #92     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[   +1 ms]            #93     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[   +2 ms] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[   +1 ms] Script 'C:\AndroidStudio\flutter_sdk\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904
[   +2 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:compileFlutterBuildDebug'.
[   +1 ms] > Process 'command 'C:\AndroidStudio\flutter_sdk\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 18s
[ +409 ms] Running Gradle task 'assembleDebug'... (completed in 19.7s)
[  +11 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 21,050ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +257 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[   +8 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
`

@kangwang1988 

git patch 成功，然后也删除了 rm bin/cache/flutter_tools.stamp。运行过flutter doctor.
由于拉不下来 git@github.com:alibaba-flutter/sdk.git 这个地址，所以换成了 issues 中的 https://gitee.com/crazydroid2014/sdk.git

然后运行 flutter run 就出错了

**Comment by fightcoder** [comment]
windows上依赖路径问题，1.20.4 -1.23.0-7.0pre版本在windows上会出现，目前master中patch中已经修改了，遇到类似issue的同学可以自己换个patch即可。

**Comment by JsonYuu** [comment]
> windows上依赖路径问题，1.20.4 -1.23.0-7.0pre版本在windows上会出现，目前master中patch中已经修改了，遇到类似issue的同学可以自己换个patch即可。

这个 已经解决了，非常感谢。

这个issue 可以close 了
