### ISSUE TITLE
在release模式下，call library级别的方法，编译出错。

### ISSUE THREAD

**Issue by galaxybruce** [alibaba-flutter/aspectd#12]
@kangwang1988  
反复测试发现一个问题，我给一个library方法添加call aop，debug模式下能正常编译，而且运行结果也正确。release模式下，出现“Dart snapshot generator failed with exit code -6”错误，生成的app.dill文件，转为txt查看了下，也是正确的，但是最后在flutter/bin/flutter中出错。
以下是我的测试代码：
![image](https://user-images.githubusercontent.com/2462686/64148005-b7ef5180-ce54-11e9-8cd5-b5a197bb01f1.png)

![image](https://user-images.githubusercontent.com/2462686/64148030-c63d6d80-ce54-11e9-8521-cb980dc8fd39.png)

错误日志：
![image](https://user-images.githubusercontent.com/2462686/64148061-dbb29780-ce54-11e9-936d-4490f2ab2035.png)

**Comment by kangwang1988** [comment]
@galaxybruce 
我看了下最新的flutter master代码:
```shell
kylewong@KyleWongdeMacBook-Pro flutter % flutter doctor -v
KWLM:doctor -v
[✓] Flutter (Channel master, v1.9.8-pre.54, on Mac OS X 10.15 19A546d, locale en-CN)
    • Flutter version 1.9.8-pre.54 at /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 16fcb83fec (4 hours ago), 2019-09-02 23:44:41 -0400
    • Engine revision e7f9ef6aa0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)
```
下是没有问题的，
Demo代码:
main.dart
```dart
void appInit() async{
}

void main() {
//  appInit();
  runApp(MyApp());
}
```

```dart
import 'package:aspectd/aspectd.dart';

@Aspect()
@pragma("vm:entry-point")
class ExecuteDemo {
  @pragma("vm:entry-point")
  ExecuteDemo();

  @Execute("package:example/main.dart", "_MyHomePageState", "-_incrementCounter")
  @pragma("vm:entry-point")
  void _incrementCounter(PointCut pointcut) {
    pointcut.proceed();
    print('[KWLM1] called!');
  }

  @Execute("package:example/main.dart", "", "+appInit")
  @pragma("vm:entry-point")
  void appInit(PointCut pointcut) {
    pointcut.proceed();
    print('[KWLM2] called!');
  }
}
```

**Comment by galaxybruce** [comment]
我使用的的flutter版本是1.7.8 
Execute是正常的，Call不可以。

**Comment by kangwang1988** [comment]
@galaxybruce 
appInit的aop方法需要声明是static的。我刚更新了下README，框架本身没有bug.

**Comment by itlwy** [comment]
@galaxybruce 你好，我现在编译release也你这个类似的错，debug是正常的，请问你那都解决了吗？
