### ISSUE TITLE
啥时候适配 2.5.0

### ISSUE THREAD

**Issue by GvcZhang** [alibaba-flutter/aspectd#132]
@kangwang1988 
Flutter 2.5.0 对应的 dart 对 ast 部分 api 进行了大量的改动，目前对其适配产生了一定的影响，是否可以尽快适配。

Dart 2.14.2 版本，删除了：`MethodInvocation` 和 `PropertyGet` 等相关的 API

**Comment by lancexin** [comment]
看了一下源码,或许可以用InstanceInvocation 和 InstanceGet 代替

**Comment by GvcZhang** [comment]
@lancexin 我这边研究了一下，Flutter 2.5.0 已经使用这两个进行了替换，不过我在 2.2.3 上部分逻辑使用这两个 API 验证，总是有很多问题，您那边有亲自验证吗？

**Comment by lancexin** [comment]
@GvcZhang 我也是昨天才有改造的想法,还没来得及研究,但是我有这方面的想法,能否加个vx?可以发我邮箱 lance.xin@me.com 我们详细探讨一下

**Comment by GvcZhang** [comment]
@lancexin 发你邮件了。有兴趣的朋友可以加我一起研究(base64)：bXluYW1lX3poYW5nd2Vp

**Comment by GvcZhang** [comment]
目前自身已对 Execute Hook 方式做了适配。
