### ISSUE TITLE
AspectD 非官方交流群

### ISSUE THREAD

**Issue by GvcZhang** [alibaba-flutter/aspectd#134]
应该有不少人或者公司在使用 AspectD 做埋点，我创建了一个微信群，给大家一个交流平台，用于咨询分享以及此项目迭代，欢迎各位加入：
<img width="207" alt="image" src="https://user-images.githubusercontent.com/45255699/178467675-d277e72d-7423-4655-9f4e-ff8f2e8e062e.png">

**Comment by littlezhuang** [comment]
有最新二维码么？我想进群一起交流下

**Comment by GvcZhang** [comment]
@littlezhuang 可以加我微信：myname_zhangwei

**Comment by GvcZhang** [comment]
上述二维码无时间限制。
