### ISSUE TITLE
bug  在flutter1.5.4版本上，aop_transformer_wrapper.dart文件189行执行报错

### ISSUE THREAD

**Issue by ckdgit** [alibaba-flutter/aspectd#19]
修改为cls **?**.name,(cls?.parent as Library) **?**.importUri.toString()后执行成功

原因是pragma("vm:entry-point")这个解析时出了问题

log
`
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AopWrapperTransformer._processAopMember (file:../aspectd-master/transformer/plugins/aop/aop_transformer_wrapper.dart:189:69)
#2      AopWrapperTransformer._resolveAopProcedures (file:///Users/chenkang/Demo/aspectd-master/transformer/plugins/aop/aop_transformer_wrapper.dart:131:38)
#3      AopWrapperTransformer.transform (file:../aspectd-master/transformer/plugins/aop/aop_transformer_wrapper.dart:20:5)
#4      TransformerWrapper.transform (file:../aspectd-master/transformer/transformer_wrapper.dart:12:27)
#5      main (file:../aspectd-master/tool/starter.dart:44:22)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
`

**Comment by kangwang1988** [comment]
@ckdgit 
Thanks. I've fixed the issue you mentioned.
