### ISSUE TITLE
dart bin/dump_kernel.dart 

### ISSUE THREAD

**Issue by xingyong723** [alibaba-flutter/aspectd#21]
dart bin/dump_kernel.dart  app.dill   app.dill.txt 为啥我这条命令一直执行不成功？
需要什么配置？

**Comment by kangwang1988** [comment]
@xingyong723 
Can you paste the log in details for `dart bin/dump_kernel.dart app.dill app.dill.txt `

**Comment by xingyong723** [comment]
* 命令： dart ~/Downloads/sdk-master/pkg/vm/bin/dump_kernel.dart  app.dill app.dill.txt

执行结果如下：
Unhandled exception:
Unexpected Kernel version 29 (expected 34).
#0      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:468:7)
#1      main (file:///Users/xxxx/Downloads/sdk-master/pkg/vm/bin/dump_kernel.dart:47:40)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by kangwang1988** [comment]
You should make sure that the dart-sdk you're using matches your flutter version.
```shell
cat /Users/kylewong/Codes/Flutter/flutter/bin/cache/dart-sdk/revision 
f020ce5d23a50c05b10c372d99a3f7a878420c78
```
The sha you get for your flutter-sdk should exactly match your dart repo.
It would be resolved after you get the right dart dk.
