### ISSUE TITLE
Problem running the aop project

### ISSUE THREAD

**Issue by maheshmnj** [alibaba-flutter/aspectd#27]
I have tried running the ```example project```,but its not calling the aop from main.dart,do we need to make any additional configurations to call the AOP?
My Understanding is that when any function in ```main.dart``` gets called say e.g ```_incrementCounter()``` then the method in ```aop_impl.dart()``` on line no 95 ```instanceUniversalHook()``` must get called but its not calling it.
Some additional details on how to call AOP implementation from our main project would be really helpful.

**Comment by kangwang1988** [comment]
@maheshmnj 
Can you paste the result for command "flutter doctor -v", please?

**Comment by kangwang1988** [comment]
Let's track this issue under https://github.com/alibaba-flutter/aspectd/issues/26
