### ISSUE TITLE
Transformer terminated unexpectedly.

### ISSUE THREAD

**Issue by Ivonhoe** [alibaba-flutter/aspectd#28]
使用aspectd v1.5.4分支代码，运行example正常，尝试在项目工程中使用aspectd方案，编译失败，提示 **Transformer terminated unexpectedly.** 

想问下有什么方法可以排查转换失败的具体原因？感谢！

→ flutter doctor -v                                                                                                       [d3640fa8]
[✓] Flutter (Channel v1.5.4-hotfixes, v1.5.4-hotfix.2-pre.1, on Mac OS X 10.14.5 18F2058, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2-pre.1 at /Users/ivonhoe/Flutter/flutter
    • Framework revision 953bbe2ccd (7 个月前), 2019-05-02 09:59:16 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/ivonhoe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/ivonhoe/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 40.2.3
    • Dart plugin version 192.7402

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • SM N9008                  • 004241ed      • android-arm • Android 5.0 (API 21)
    • A0001                     • b2175f20      • android-arm • Android 5.1.1 (API 22)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.

**Comment by Ivonhoe** [comment]
已解决。
aopAnnoLibrary 可能为空，当注解的importUri所对应的library并不存在时。

![image](https://user-images.githubusercontent.com/5706813/68861919-79fd8c00-0727-11ea-9ba4-2d848b1835c3.png)

**Comment by kangwang1988** [comment]
@Ivonhoe 
Thanks for your feedback.
In the latest master branch, this problem doesn't exist as refactored.
Welcome to file a pr to fix it in v1.5.4 if you would like.
