### ISSUE TITLE
详细的使用说明文档有没有

### ISSUE THREAD

**Issue by kankedelangzi** [alibaba-flutter/aspectd#3]

**Comment by kangwang1988** [comment]
@kankedelangzi 
README已经介绍了很多，包括使用步骤和语法，请问你是觉得哪里不明白呢？我看要如何完善下。

**Comment by kankedelangzi** [comment]
> @kankedelangzi
> README已经介绍了很多，包括使用步骤和语法，请问你是觉得哪里不明白呢？我看要如何完善下。

照着你写的步骤运行不起来，连包的依赖都安装不上。请提供一个能直接Git下载的demo

**Comment by kangwang1988** [comment]
仓库下就有example。
你说的依赖安装不上具体什么日志或者表现，哪个依赖安装不上？
@kankedelangzi

**Comment by MMMzq** [comment]
请问一下能再详细说一下第4步吗?

**Comment by kangwang1988** [comment]
@MMMzq 
请提供下你使用的flutter版本信息。
此外，其实这个patch很小，虽然里面包含三个文件的内容，但核心的packages/flutter_tools/lib/src/aspectd.dart是新增文件，其内容参见gist
https://gist.github.com/kangwang1988/8c1b40f137cd3e269b782f6c2716ccdc

其他两个对于已有文件的修改可能会造成不同版本flutter下的git apply冲突，但其实其逻辑很简单
packages/flutter_tools/lib/src/commands/build_aot.dart的变更如下:
<img width="1036" alt="Screen Shot 2019-07-09 at 9 44 16 PM" src="https://user-images.githubusercontent.com/817851/60893418-7ba7d680-a293-11e9-929c-6e94dbab1faf.png">

packages/flutter_tools/lib/src/commands/build_bundle.dart的变更如下:
<img width="1037" alt="Screen Shot 2019-07-09 at 9 44 23 PM" src="https://user-images.githubusercontent.com/817851/60893428-7f3b5d80-a293-11e9-9025-f600e5a639f9.png">

这两个其实是一种hardcode的hook机制，是目前唯一存在侵入性的地方，目前是patch的形式。但我已然提了flutter的pr来提供原生的hook机制，这样后面这一块的侵入性也就可以干掉了。

**Comment by MMMzq** [comment]
@kangwang1988 

flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (2 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

这个是我报错的那个版本信息。

我晚上回去我自己尝试去直接去修改👌

**Comment by kangwang1988** [comment]
@MMMzq 
不知道你那边怎么了，我这里是git patch是ok的，
```dart
(base) kylewong@KyleWongs-MacBook-Pro flutter % git apply --3way /Users/kylewong/Codes/Flutter/aspectd/0001-aspectd.patch 
error: patch failed: packages/flutter_tools/lib/src/commands/build_bundle.dart:4
Falling back to three-way merge...
Applied patch to 'packages/flutter_tools/lib/src/commands/build_bundle.dart' cleanly.
(base) kylewong@KyleWongs-MacBook-Pro flutter % flutter doctor -v                                                         
[!] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.15 19A501i, locale en-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/kylewong/Codes/Flutter/flutter
    • Framework revision 7a4c33425d (2 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    ✗ Downloaded executables cannot execute on host.
```

**Comment by kangwang1988** [comment]
鉴于README提供了足够的使用步骤和语法信息，关掉这个issue.
