### ISSUE TITLE
不支持mixin

### ISSUE THREAD

**Issue by ZongwenSun** [alibaba-flutter/aspectd#31]
假设有下面的类结构
```
class A {
	void fa(){}
}

class B {
	void fb();
}

class C with A,B {
	void fc(){}
}
```
直接改A的fa方法是无效的，需要改_C&A类的fa方法才可以。

**Comment by kangwang1988** [comment]
@ZongwenSun 
Please provide your scenario in details, for example, which function you would like to operate, what's your expected output and how do you want to use aspectd to do hook.

**Comment by ZongwenSun** [comment]
@kangwang1988  I want to hook the method below:
path : package:flutter/src/gestures/binding.dart
class : GestureBinding
method: dispatchEvent
