### ISSUE TITLE
Flutter 1.9.1+hotfix.6  apply patch 失败

### ISSUE THREAD

**Issue by loDANve** [alibaba-flutter/aspectd#32]
环境：
Flutter 1.9.1+hotfix.6
AspectD v1.9.1
执行命令 git apply --3way /Users/zhaoxy/Desktop/code/aspectd/0001-aspectd.patch 报错如下：

Falling back to three-way merge...
Applied patch to 'packages/flutter_tools/lib/src/aspectd.dart' cleanly.
error: patch failed: packages/flutter_tools/lib/src/commands/build_aot.dart:5
Falling back to three-way merge...
Applied patch to 'packages/flutter_tools/lib/src/commands/build_aot.dart' cleanly.
error: patch failed: packages/flutter_tools/lib/src/commands/build_bundle.dart:4
Falling back to three-way merge...
Applied patch to 'packages/flutter_tools/lib/src/commands/build_bundle.dart' cleanly.

**Comment by kangwang1988** [comment]
![image](https://user-images.githubusercontent.com/817851/69525942-2818f980-0fa4-11ea-9451-9ce8466e5382.png)

I think the error message you paste error is not actually an error, just some hint log from git when applying a patch.
