### ISSUE TITLE
AspectD for Dart instead of AspectD for Flutter

### ISSUE THREAD

**Issue by matthewadams** [alibaba-flutter/aspectd#35]
Apologies, but this is more of a question that a bug report, but I don't know where discussion for this repo goes on.  I'm a total noob to Dart as I write this.  I can't tell if AspectD can be used outside of Flutter projects.

So, can AspectD be used in vanilla Dart projects that have nothing to do with Flutter or any other UI framework?

**Comment by kangwang1988** [comment]
@matthewadams Of course, you can. As long as there is a dill file including ast tree(dart), you can apply aspectd.
The key steps to apply a transformation include two part:
Suppose you're in the aspectd root directory.
1. Generate a transform snapshot:
```shell
aspectd % pub upgrade --verbose
aspectd % dart --snapshot=snapshot/aspectd.dart.snapshot tool/starter.dart
```
2. Transform the dill file using the newly generated snapshot/aspectd.dart.snapshot
```shell
aspectd % dart snapshot/aspectd.dart.snapshot --input kernel_blob.bin --sdk-root flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --output app.aspectd.dill
```
Here, the kernel_blob.bin is actually a dill file including your business logic(app) and aop logic(aop_impl), in other words, you should make sure you have two packages app and aop_impl(who's main function will import the app'main), and compile the aop_impl into dill file. Then calling the transformation on kernel_blob.bin and you'll get a app.aspectd.dill. Then you can get what you want by running app.aspectd.dill.
There might be still some job, but not much. If you can give a demo project and we might make it work.
