### ISSUE TITLE
Flutter v1.9.1+hotfix.2 apply patch 失败

### ISSUE THREAD

**Issue by itlwy** [alibaba-flutter/aspectd#36]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

--------------------------------

git apply --3way /e/flutter/aspectd-1.9.1/0001-aspectd.patch
Falling back to three-way merge...
Applied patch to 'packages/flutter_tools/lib/src/aspectd.dart' cleanly.
error: patch failed: packages/flutter_tools/lib/src/commands/build_aot.dart:5
Falling back to three-way merge...
Applied patch to 'packages/flutter_tools/lib/src/commands/build_aot.dart' cleanly.
error: patch failed: packages/flutter_tools/lib/src/commands/build_bundle.dart:4
Falling back to three-way merge...
Applied patch to 'packages/flutter_tools/lib/src/commands/build_bundle.dart' cleanly.

--------------------------------

$ flutter doctor -v
Building flutter tool...
/d/src/flutter/bin/flutter: line 46: /d/src/flutter/bin/cache/dart-sdk/bin/pub: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

**Comment by kangwang1988** [comment]
@itlwy 
Please use https://github.com/alibaba-flutter/aspectd/tree/v1.9.1
