### ISSUE TITLE
无法hook住dart:io中的代码

### ISSUE THREAD

**Issue by binghan-iOS** [alibaba-flutter/aspectd#40]
无法hook住dart:io中的代码：

调用HttpClient的代码：

void _getIPAddress() async {
    var url = 'https://httpbin.org/ip';
    var httpClient =  HttpClient();

    String result;
    try {
      var request = await httpClient.getUrl(Uri.parse(url));
      var response = await request.close();
      if (response.statusCode == HttpStatus.OK) {
        var json = await response.transform(utf8.decoder).join();
        dynamic data = jsonDecode(json);
        result = data['origin'];
      } else {
        result =
            'Error getting IP address:\nHttp status ${response.statusCode}';
      }
    } catch (exception) {
      result = 'Failed getting IP address';
    }
    print(result);
  }

HttpClient属于dart.io库，下面的函数无法出发。

@Call("dart:io",'.*', '-.+', isRegex: true) 
  @pragma("vm:entry-point")
  dynamic instanceUniversalHook(PointCut pointcut) {
    print('[KWLM4]instanceUniversalHook:${pointcut.target}-${pointcut.function}-${pointcut.namedParams}-${pointcut.positionalParams}');
    dynamic obj = pointcut.proceed();
    return obj;
  }
  @Call("dart:io",'.*', "+^.*\$", isRegex: true)
  @pragma("vm:entry-point")
  static dynamic staticUniversalHook(PointCut pointcut) {
    print('[KWLM5]staticUniversalHook:${pointcut.target}-${pointcut.function}-${pointcut.namedParams}-${pointcut.positionalParams}');
    dynamic obj = pointcut.proceed();
    return obj;
  }

**Comment by kangwang1988** [comment]
You can try with aspectd 1.0.0 for flutter @ stable v1.22.1 to see if it works.
Besides, please verify it under flutter's release mode.
