### ISSUE TITLE
Debug环境下Hook设置了默认参数的构造函数崩溃

### ISSUE THREAD

**Issue by Liujingguang** [alibaba-flutter/aspectd#41]
Hook的代码：
  @Call("package:flutter/src/widgets/gesture_detector.dart", "GestureDetector",
      "+GestureDetector")
  @pragma("vm:entry-point")
  static dynamic GestureDetector(PointCut pointcut) {
    print('[KWLM-ljg]: Hook GestureDetector Constructor!');
    return pointcut.proceed();
  }

--------------------

系统GestureDetector的构造函数：
GestureDetector({
  Key key,
  this.child,
  this.onTap,
  ...
  this.excludeFromSemantics = false,
  this.dragStartBehavior = DragStartBehavior.start,
}) : assert(excludeFromSemantics != null),
      assert(dragStartBehavior != null),
      assert(() {
        ...
}

--------------------

分析处理后的dill文件
return new ges::GestureDetector::•(
  key: this.namedParams.[]("key") as key::Key*,
  child: this.namedParams.[]("child") as fra::Widget*,
  onTap: this.namedParams.[]("onTap") as () →* void, 
  ...
  excludeFromSemantics: this.namedParams.[]("excludeFromSemantics") as core::bool*, 
  dragStartBehavior: this.namedParams.[]("dragStartBehavior") as rec::DragStartBehavior*, 
  $creationLocationd_0dea112b090073317d4: this.namedParams.[]("\$creationLocationd_0dea112b090073317d4") as wid::_Location*);

excludeFromSemantics和dragStartBehavior赋值为null。
测试debug环境是有问题的，release是正常的，因为release会删除assert。
在debug手动配置默认值后也是正常的，代码如下：

static dynamic GestureDetector(PointCut pointcut) {
  print('[KWLM-ljg]: Hook GestureDetector Constructor!');
  pointcut.namedParams['excludeFromSemantics'] = false;
  pointcut.namedParams['dragStartBehavior'] = DragStartBehavior.start;
  return pointcut.proceed();
}

希望能优化该问题。

**Comment by kangwang1988** [comment]
Try aspectd 1.0.0 for flutter @stable v1.22.1
