### ISSUE TITLE
与flutter_booster一起使用冲突

### ISSUE THREAD

**Issue by fightcoder** [alibaba-flutter/aspectd#42]
与flutter_boost单独使用都没问题，一起使用后，编译报错：
 warning: The iOS Simulator deployment target is set to 4.3, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'FMDB')
    warning: Capabilities for Runner may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'Runner')
    /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/include/dispatch/queue.h:1352:1: note: 'dispatch_queue_set_specific' has been marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
    ^
    /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning: 'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/include/dispatch/queue.h:1408:1: note: 'dispatch_get_specific' has been marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    dispatch_get_specific(const void *key);
    ^
    /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose 'dispatch_get_specific' in an @available check to silence this warning
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/include/sqlite3.h:8245:16: note: 'sqlite3_wal_checkpoint_v2' has been marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/xxx/flutter/flutter_wallet/.ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.

    Compiler message:
    Error: Could not resolve the package 'flutter_boost' in 'package:flutter_boost/flutter_boost.dart'.
    ../lib/main.dart:8:8: Error: Not found: 'package:flutter_boost/flutter_boost.dart'
    import 'package:flutter_boost/flutter_boost.dart';
           ^
    Error: Could not resolve the package 'flutter_boost' in 'package:flutter_boost/channel/boost_channel.dart'.
    ../lib/page/goods_coupon_page.dart:2:8: Error: Not found: 'package:flutter_boost/channel/boost_channel.dart'
    import 'package:flutter_boost/channel/boost_channel.dart';
           ^
    ../lib/main.dart:72:5: Error: Getter not found: 'FlutterBoost'.
        FlutterBoost.singleton.addBoostContainerLifeCycleObserver(
        ^^^^^^^^^^^^
    ../lib/main.dart:73:10: Error: 'ContainerLifeCycle' isn't a type.
            (ContainerLifeCycle state, BoostContainerSettings settings) {
             ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:73:36: Error: 'BoostContainerSettings' isn't a type.
            (ContainerLifeCycle state, BoostContainerSettings settings) {
                                       ^^^^^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:90:20: Error: Getter not found: 'ContainerLifeCycle'.
          if (state == ContainerLifeCycle.Init) {
                       ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:92:27: Error: Getter not found: 'ContainerLifeCycle'.
          } else if (state == ContainerLifeCycle.Destroy) {
                              ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:94:27: Error: Getter not found: 'ContainerLifeCycle'.
          } else if (state == ContainerLifeCycle.Disappear) {
                              ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:96:27: Error: Getter not found: 'ContainerLifeCycle'.
          } else if (state == ContainerLifeCycle.Background) {
                              ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:100:5: Error: Getter not found: 'FlutterBoost'.
        FlutterBoost.singleton.registerPageBuilders({
        ^^^^^^^^^^^^
    ../lib/main.dart:72:5: Error: The getter 'FlutterBoost' isn't defined for the class '_WalletAppState'.
     - '_WalletAppState' is from 'package:flutter_module/main.dart' ('../lib/main.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'FlutterBoost'.
        FlutterBoost.singleton.addBoostContainerLifeCycleObserver(
        ^^^^^^^^^^^^
    ../lib/main.dart:90:20: Error: The getter 'ContainerLifeCycle' isn't defined for the class '_WalletAppState'.
     - '_WalletAppState' is from 'package:flutter_module/main.dart' ('../lib/main.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'ContainerLifeCycle'.
          if (state == ContainerLifeCycle.Init) {
                       ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:92:27: Error: The getter 'ContainerLifeCycle' isn't defined for the class '_WalletAppState'.
     - '_WalletAppState' is from 'package:flutter_module/main.dart' ('../lib/main.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'ContainerLifeCycle'.
          } else if (state == ContainerLifeCycle.Destroy) {
                              ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:94:27: Error: The getter 'ContainerLifeCycle' isn't defined for the class '_WalletAppState'.
     - '_WalletAppState' is from 'package:flutter_module/main.dart' ('../lib/main.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'ContainerLifeCycle'.
          } else if (state == ContainerLifeCycle.Disappear) {
                              ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:96:27: Error: The getter 'ContainerLifeCycle' isn't defined for the class '_WalletAppState'.
     - '_WalletAppState' is from 'package:flutter_module/main.dart' ('../lib/main.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'ContainerLifeCycle'.
          } else if (state == ContainerLifeCycle.Background) {
                              ^^^^^^^^^^^^^^^^^^
    ../lib/main.dart:100:5: Error: The getter 'FlutterBoost' isn't defined for the class '_WalletAppState'.
     - '_WalletAppState' is from 'package:flutter_module/main.dart' ('../lib/main.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'FlutterBoost'.
        FlutterBoost.singleton.registerPageBuilders({
        ^^^^^^^^^^^^
    ../lib/main.dart:164:16: Error: Getter not found: 'FlutterBoost'.
          builder: FlutterBoost.init(postPush: _onRoutePushed),
                   ^^^^^^^^^^^^
    ../lib/main.dart:164:16: Error: The getter 'FlutterBoost' isn't defined for the class '_WalletAppState'.
     - '_WalletAppState' is from 'package:flutter_module/main.dart' ('../lib/main.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'FlutterBoost'.
          builder: FlutterBoost.init(postPush: _onRoutePushed),
                   ^^^^^^^^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_boost%2Fflutter_boost.dart; message=StandardFileSystem only supports file:* and data:* URIs)
    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:578:37)
    <asynchronous suspension>
    #2      writeDepfile (package:vm/kernel_front_end.dart:755:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile (package:vm/frontend_server.dart:407:15)
    <asynchronous suspension>
    #4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29:22)
    <asynchronous suspension>
    #5      starter (package:frontend_server/server.dart:127:27)
    <asynchronous suspension>
    #6      main (file:///b/s/w/ir/k/src/flutter/frontend_server/bin/starter.dart:8:30)
    <asynchronous suspension>
    #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
    #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

    Compiler failed on /Users/xxx/flutter/flutter_wallet/aspectd_impl/lib/aspectd_impl.dart
    Failed to package /Users/xxx/flutter/flutter_wallet.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description

flutter doctor信息如下：

[✓] Flutter (Channel stable, v1.9.1, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)
    • Flutter version 1.9.1 at /Users/xxx/flutter/flutter
    • Framework revision c382b8e990 (9 months ago), 2019-08-18 15:22:36 -0400
    • Engine revision 5540684152
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone Xʀ • 0D623F81-C315-4F5A-8267-F8936B55FFEA • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.

个人猜测关键信息在：
![image](https://user-images.githubusercontent.com/19933500/81179874-dc4f8f00-8fdc-11ea-8079-0d485260a033.png)
![image](https://user-images.githubusercontent.com/19933500/81179926-f1c4b900-8fdc-11ea-8408-74648400997f.png)

**Comment by kelciej** [comment]
@fightcoder 您好，您这个问题解决了吗？

**Comment by GvcZhang** [comment]
@fightcoder 您是如何解决的呢？
