### ISSUE TITLE
Inject方法可以用在自己写的方法中么

### ISSUE THREAD

**Issue by kelciej** [alibaba-flutter/aspectd#44]
您好，
请问一下@inject可以注入到自己写的方法中么？
比方说 注入到 官方 example 的_incrementCounter 中，
![image](https://user-images.githubusercontent.com/19542871/82557968-4badad00-9b9f-11ea-932f-9bf5a3ff1274.png)
比方说想在【91】行写入一个输出

`  @Inject("package:example/lib/main.dart","_MyHomePageState","-_incrementCounter",lineNum:91)

@pragma("vm:entry-point")

static void counterHook() {

int count;//Aspectd Ignore

int _counter;//Aspectd Ignore

print("[KWLM12]:count:$count,counter:$_counter");

//【91】行 }`

但是无法注入
生成文件app.aspectd.dill.txt显示 如下图，
![image](https://user-images.githubusercontent.com/19542871/82558945-56694180-9ba1-11ea-9287-ec75b29abd7c.png)

**Comment by kelciej** [comment]
自己尝试写了一些inject，但是出现了有的时候能够 inject成功，有的时候 inject不成功的情况。
请教一下，inject的位置（行数）有什么主要注意的地方么？，比方说不能inject在空行中

**Comment by kangwang1988** [comment]
Inject is a sophisticated thing and I don't think it's robust enough to use.
You can try it under aspectd 1.0.0 for flutter v1.22.1 and i may have a look at it given a reproducible mvp.

**Comment by dudumuta** [comment]
> 自己尝试写了一些inject，但是出现了有的时候能够 inject成功，有的时候 inject不成功的情况。
> 请教一下，inject的位置（行数）有什么主要注意的地方么？，比方说不能inject在空行中

我想咨询下大佬，我自己写了个方法，然后按照文档增加了注解，如何使之生效呢？怎么触发dill的生成？

**Comment by FloydP** [comment]
@kelciej Hi，我也在官方example 尝试了Inject , 在我的例子里变量并不会 因为//Aspectd Ignore 在hook时被忽略，你是如何成功使用的，能否告诉我一下？
