### ISSUE TITLE
请教，如何调试aspectd.dart

### ISSUE THREAD

**Issue by itlwy** [alibaba-flutter/aspectd#45]
你好，我apply patch 后，使用此方法：[debug flutter_tools](https://github.com/flutter/flutter/wiki/The-flutter-tool#debugging-the-flutter-command-line-tool) 开启ide调试，但是在`AspectdHook.isAspectdEnabled`方法里断点并没有执行到，请问要如何才能调试这方面的源码呢？期待解答，谢谢

**Comment by kangwang1988** [comment]
1. edit flutter_tools.dart with below:
import 'package:flutter_tools/executable.dart' as executable;

void main(List<String> args) {
  print("[KWLM]:${args.join(' ')}");
  executable.main(args);
}

2. run flutter run --verbose --debug and you may see log like:
[KWLM]:--verbose assemble --depfile /Users/kylewong/Desktop/AOP/example/build/app/intermediates/flutter/release/flutter_build.d --output
/Users/kylewong/Desktop/AOP/example/build/app/intermediates/flutter/release -dTargetFile=/Users/kylewong/Desktop/AOP/example/lib/main.dart
-dTargetPlatform=android -dBuildMode=release android_aot_bundle_release_android-arm64

3. debug flutter_tools with arguments above with the working directory set to your flutter project.

It's supposed that you'll be able to catch the breakpoint. It also can be skipped while the dill cache check success as there is no changes detected, you can delete the dill file to invalid it.

**Comment by GvcZhang** [comment]
@itlwy 你好，可否指教一下如何调试
