### ISSUE TITLE
win7环境下生成aspectd.dart.snapshot会出错

### ISSUE THREAD

**Issue by itlwy** [alibaba-flutter/aspectd#46]
作者你好，我正在使用你的框架，发现patch里的`aspectd.dart`源码里的`generateAspectdSnapshot`方法调用的`sdkBinaryName('dart')`获取的是dart.bat可执行文件，实际上`Cache.flutterRoot/bin/cache/dart-sdk/`目录下只有`dart.exe`，所以会报文件找不到的错误。
我这边将 `sdkBinaryName('dart')` 改为：`artifacts.getArtifactPath(Artifact.engineDartBinary)`，运行正常打包注入，代码片段如下：
```
   static Future<void> generateAspectdSnapshot(
      String aspectdSnapshotPath) async {
    ...
    if (pubspecLockFile.existsSync()) {
      await processManager.run(<String>[
        artifacts.getArtifactPath(Artifact.engineDartBinary),
//        sdkBinaryName('dart'),
        '--snapshot=snapshot/aspectd.dart.snapshot',
        'tool/starter.dart'
      ], workingDirectory: snapshotDir.parent.path);
    }
  }
```

**Comment by itlwy** [comment]
补充：分支是v1.12.13

**Comment by kangwang1988** [comment]
You're welcome to provide a pr.
