### ISSUE TITLE
hook自定义枚举类型报错

### ISSUE THREAD

**Issue by kelciej** [alibaba-flutter/aspectd#47]
您好，尝试用了demo中的instanceUniversalHook方法
`dynamic instanceUniversalHook(PointCut pointcut) {
    print('mmm,Before:${pointcut.target}-${pointcut.function}}');
    dynamic obj = pointcut.proceed();
    return obj;
  }`

其中某些页面的参数是自定义的枚举类型，这里报错Invalid argument(s),希望能改进，谢谢！

某页面为Tab 页，进入该页面执行instanceUniversalHook时，会报错 StackOverFlow
错误如下：
![image](https://user-images.githubusercontent.com/19542871/82869613-20410e80-9f61-11ea-8eca-ed6b4872d910.png)

**Comment by kangwang1988** [comment]
You can try aspectd 1.0.0 for flutter stable v1.22.1
