### ISSUE TITLE
能修改Widget的构造函数吗？

### ISSUE THREAD

**Issue by BoomZhang** [alibaba-flutter/aspectd#48]
通过Aspectd怎么修改Widget的构造函数？
Execute的参数是什么规则？
没有生效
@Execute("package:flutter/framework.dart", "Widget", "+Widget")
   @pragma("vm:entry-point")
   dynamic receiveTapped(PointCut pointcut) {
     dynamic obj = pointcut.proceed();
     print('Execute constructor method!');
     pointcut.proceed();
     return obj;
   }

**Comment by kangwang1988** [comment]
It's designed to support the constructor logic.
Try 0.9.9 for flutter @ stable v1.20.4
or 1.0.0 for flutter @ stable v1.22.1
