### ISSUE TITLE
Error: Not found: 'dart:ui'

### ISSUE THREAD

**Issue by dudumuta** [alibaba-flutter/aspectd#51]
按照readme的步骤操作了多次，执行dart --snapshot=aspectd_impl.dill lib/aspectd_impl.dart时报Error: Not found: 'dart:ui'，请大神帮忙解决下

**Comment by kangwang1988** [comment]
Try use 1.0.0 over Flutter @ stablev1.22.1

**Comment by dudumuta** [comment]
咨询个问题，demo是跑起来了，但是我想自己写几个aop的方法，如何使之生效？
