### ISSUE TITLE
kernel 0.3.29 from git git@github.com:alibaba-flutter/sdk.git at eb9d9e in pkg/kernel

### ISSUE THREAD

**Issue by robin0822** [alibaba-flutter/aspectd#55]
您好 请问我在aspectd 目录下  flutter packages get 之后   出现这个错误 

Target kernel_snapshot failed: FileSystemException: Cannot open file, path = '/Users/quyanhui/Documents/aspectd/aspectd_impl/.packages' (OS Error: No such file or directory, errno = 2)
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by kangwang1988** [comment]
在aspectd, aspectd_impl,example目录下删除.packages pubspec.lock
然后在你出错的文件夹执行pub get --verbosity=all ，还有问题的话，贴出来详细日志。

**Comment by robin0822** [comment]
我demo  运行起来了 


但是在我集成项目时候 出现错误  错误日志打在了  aspect_imp  目录下  flutter_01.log  log 日志如下：


Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter assemble --output=/Users/quyanhui/Desktop/app/app_all/.ios/Flutter/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=debug -dIosArchs=arm64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation= -dDartObfuscation=false -dEnableBitcode= --DartDefines= -dExtraFrontEndOptions= debug_ios_bundle_flutter_assets

## exception

RangeError: RangeError: Value not in range: 36

```
#0      _StringBase.substring (dart:core-patch/string_patch.dart:385:7)
#1      AspectdHook.runBuildDillCommand (package:flutter_tools/src/aspectd.dart:171:10)
#2      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:191:27)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#4      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#8      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5

**Comment by robin0822** [comment]
> 在aspectd, aspectd_impl,example目录下删除.packages pubspec.lock
> 然后在你出错的文件夹执行pub get --verbosity=all ，还有问题的话，贴出来详细日志。

我上面的问题 您能帮我看一下么

**Comment by kangwang1988** [comment]
调试下https://github.com/flutter/flutter/wiki/The-flutter-tool

**Comment by robin0822** [comment]
您好 我本地用 纯flutter工程 可以构建&nbsp;


集成到我自己的工程混合开发的工程 就会有


如下 报错&nbsp; 不明白具体的原因&nbsp; 求帮助


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba-flutter/aspectd"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 上午10:22
收件人:&nbsp;"alibaba-flutter/aspectd"<aspectd@noreply.github.com&gt;;
抄送:&nbsp;"偶埘蘾疍"<125346665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba-flutter/aspectd] kernel 0.3.29 from git git@github.com:alibaba-flutter/sdk.git at eb9d9e in pkg/kernel (#55)





 
调试下https://github.com/flutter/flutter/wiki/The-flutter-tool

**Comment by kangwang1988** [comment]
你可以先通过搞清楚纯flutter工程下怎么样的workflow
然后打日志看看，混合工程下问题在哪里。

**Comment by robin0822** [comment]
您好 我搞明白了&nbsp; 感谢哦 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba-flutter/aspectd"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 晚上7:27
收件人:&nbsp;"alibaba-flutter/aspectd"<aspectd@noreply.github.com&gt;;
抄送:&nbsp;"偶埘蘾疍"<125346665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba-flutter/aspectd] kernel 0.3.29 from git git@github.com:alibaba-flutter/sdk.git at eb9d9e in pkg/kernel (#55)





 
你可以先通过搞清楚纯flutter工程下怎么样的workflow
 然后打日志看看，混合工程下问题在哪里。
