### ISSUE TITLE
git apply patch 失败  v1.12.13+hotfix.9

### ISSUE THREAD

**Issue by just-for-you** [alibaba-flutter/aspectd#58]
D:\Program Files\flutter>git apply --3way D:/workspace1/aspectd/0001-aspectd.patch
error: git apply: bad git-diff - expected /dev/null on line 15

**Comment by kangwang1988** [comment]
See: https://github.com/alibaba-flutter/aspectd/issues/5#issuecomment-726062067

Closing this issue as duplicate.

**Comment by just-for-you** [comment]
done 可参考此链接 https://www.itdaan.com/tw/1dfabc5e06e2d18c2e884d320bfeb334
