### ISSUE TITLE
跑了example工程中的例子 没有效果

### ISSUE THREAD

**Issue by Knight-ZXW** [alibaba-flutter/aspectd#6]
[✓] Flutter (Channel master, v1.8.5-pre.77, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
    • Flutter version 1.8.5-pre.77 at /Users/hb/development/flutter
    • Framework revision 8e5fb8c35d (3 hours ago), 2019-08-07 22:29:24 -0400
    • Engine revision f200ee13aa
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)

flutter git 目录执行过
git apply --3way path-for-aspectd-package/0001-aspectd.patch
rm bin/cache/flutter_tools.stamp

操作

**Comment by kangwang1988** [comment]
@Knight-ZXW 
如果你确定意境应用了patch，并且删除flutter_tools.stamp，那么Building flutter tool...将会执行重新生成flutter_tools的snapshot。
之后如果没有看到效果，以flutter run为例那么有几个地方可以确认下。
a. example/aop/build/app.dill是否有生成
<img width="823" alt="Screen Shot 2019-08-08 at 5 30 52 PM" src="https://user-images.githubusercontent.com/817851/62691831-0a7a5100-ba02-11e9-920d-6ae8122b0c34.png">

b.~/.pub-cache/git中的sdk-xxx(dart源代码)和aspectd-xxx的源代码是否都存在，不为空，并且aspectd-xx/snapshot下的aspectd.dart.snapshot是否已经成功生成
<img width="1019" alt="Screen Shot 2019-08-08 at 5 33 39 PM" src="https://user-images.githubusercontent.com/817851/62692036-7c529a80-ba02-11e9-97b6-4522cf8f253c.png">

再一个，麻烦贴一下flutter run --release --verbose的全部日志哈。

**Comment by Knight-ZXW** [comment]
![屏幕快照 2019-08-08 下午8 43 28](https://user-images.githubusercontent.com/11730925/62704134-453db280-ba1d-11e9-856a-6c55b839dcf2.png)

git clone dart sdk 好慢，经常出现  error: RPC failed 而中断 .

我看了源码，有个疑问，这里为什么需要单独 从git下载dart依赖，不能直接使用 用户本地flutter路径中的dart库吗

**Comment by kangwang1988** [comment]
@Knight-ZXW 
aspectd使用的transformer需要dart-sdk本身提供的几个dart库，这些库以源码形式存在，并不在用户本身flutter的dart库中。但他们是相关的，你的flutter对应的dartsdk的源代码就是这里需要git获取的内容。

**Comment by Knight-ZXW** [comment]
@Knight-ZXW 成功下载了 dart-sdk后 ，运行 报错了


➜  example git:(master) ✗ flutter run --release --verbose
Building flutter tool...
[  +32 ms] executing: [/Users/hb/development/flutter/] git log -n 1 --pretty=format:%H
[  +55 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8e5fb8c35d869e9eba3c753eb9d1fdbc94ec9afa
[        ] executing: [/Users/hb/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +81 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.8.4-77-g8e5fb8c35
[  +12 ms] executing: [/Users/hb/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/hb/development/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +69 ms] executing: [/Users/hb/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +433 ms] executing: /Users/hb/Library/Android/sdk/platform-tools/adb devices -l
[  +12 ms] Exit code 0 from: /Users/hb/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +17 ms] executing: /Users/hb/development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +56 ms] /usr/bin/xcrun simctl list --json devices
[ +314 ms] No supported devices connected.
[  +13 ms] "flutter run" took 854ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:282:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:63:9)
<asynchronous suspension>
#39     main (file:///Users/hb/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by Knight-ZXW** [comment]
> @kangwang1988 
> aspectd使用的transformer需要dart-sdk本身提供的几个dart库，这些库以源码形式存在，并不在用户本身flutter的dart库中。但他们是相关的，你的flutter对应的dartsdk的源代码就是这里需要git获取的内容。

通过打印日志，发现不生效的原因是 访问github太慢了导致超时，
1.是连接 http://raw.githubusercontent.com/flutter/engine/xxxx/DEPS 有时候会超时

2.是  git clone dart-sdk 会超时，dart-sdk太大了，可能出现 error: RPC failed 而中断，clone不下来。

后来我通过将 dart-sdk clone到 gitee，从gitee上下载 暂时解决了该问题。

**Comment by maheshmnj** [comment]
can you please provide some detailed example on How to do logging and exception handling it can be very useful if you provide some detailed runnning example
