### ISSUE TITLE
没效果呀，真难

### ISSUE THREAD

**Issue by GvcZhang** [alibaba-flutter/aspectd#61]
折腾了一天了，这玩意到底怎么用呀，首先按照官方的 Intallation 尝试，然后运行 example 没效果。再运行 aspectd 中的 example 报错：
![image](https://user-images.githubusercontent.com/45255699/99893171-d2ab2180-2cb7-11eb-99c8-3686e3f125c7.png)

**Comment by GvcZhang** [comment]
@fightcoder 我来这里向你请教了，求帮助。从你的这篇文章跳过来的：https://juejin.cn/post/6892371163859976199#heading-8

**Comment by GvcZhang** [comment]
flutter 是 stable 1.22.4 版本，aspectd 使用最新的

**Comment by fightcoder** [comment]
> @fightcoder 我来这里向你请教了，求帮助。从你的这篇文章跳过来的：https://juejin.cn/post/6892371163859976199#heading-8

1. patch有没成功
2. Dart部分源码依赖是否成功（即`aspectd`下执行`flutter packages get -v`是否成功）
3. 报错信息不明显，运行`flutter run -v`试试
运行起来没问题的，再试试看。

**Comment by GvcZhang** [comment]
> > @fightcoder 我来这里向你请教了，求帮助。从你的这篇文章跳过来的：https://juejin.cn/post/6892371163859976199#heading-8
> 
> 1. patch有没成功
> 2. Dart部分源码依赖是否成功（即`aspectd`下执行`flutter packages get -v`是否成功）
> 3. 报错信息不明显，运行`flutter run -v`试试
>    运行起来没问题的，再试试看。

@fightcoder 

1.  patch有没成功  
![image](https://user-images.githubusercontent.com/45255699/99926328-4adb1b00-2d7c-11eb-8b68-27a298c0b4c4.png)
我这边可以确认已经patch成功了

2. `aspectd`目录下执行`flutter packages get -v` 报错信息
![image](https://user-images.githubusercontent.com/45255699/99926463-cccb4400-2d7c-11eb-9853-b8101e298ef5.png)

3.  报错信息不明显，运行`flutter run -v`试试
按照 Installation 步骤集成：aspectd_impl 使用如下方式添加的 aspectd
![image](https://user-images.githubusercontent.com/45255699/99927162-45330480-2d7f-11eb-9fb9-fdb89dd8adc8.png)
然后运行项目：
![image](https://user-images.githubusercontent.com/45255699/99927249-a22eba80-2d7f-11eb-8183-d6ab23da573a.png)
还有一些类似这样的信息：
![image](https://user-images.githubusercontent.com/45255699/99927293-d7d3a380-2d7f-11eb-96db-a31e50903155.png)

**Comment by fightcoder** [comment]
> > > @fightcoder 我来这里向你请教了，求帮助。从你的这篇文章跳过来的：https://juejin.cn/post/6892371163859976199#heading-8
> > 
> > 
> > 
> > 1. patch有没成功
> > 2. Dart部分源码依赖是否成功（即`aspectd`下执行`flutter packages get -v`是否成功）
> > 3. 报错信息不明显，运行`flutter run -v`试试
> >    运行起来没问题的，再试试看。
> 
> @fightcoder
> 
> 1. patch有没成功
>    ![image](https://user-images.githubusercontent.com/45255699/99926328-4adb1b00-2d7c-11eb-8b68-27a298c0b4c4.png)
>    我这边可以确认已经patch成功了
> 2. `aspectd`目录下执行`flutter packages get -v` 报错信息
>    ![image](https://user-images.githubusercontent.com/45255699/99926463-cccb4400-2d7c-11eb-9853-b8101e298ef5.png)
> 3. 报错信息不明显，运行`flutter run -v`试试
>    按照 Installation 步骤集成：aspectd_impl 使用如下方式添加的 aspectd
>    ![image](https://user-images.githubusercontent.com/45255699/99927162-45330480-2d7f-11eb-9fb9-fdb89dd8adc8.png)
>    然后运行项目：
>    ![image](https://user-images.githubusercontent.com/45255699/99927249-a22eba80-2d7f-11eb-8183-d6ab23da573a.png)
>    还有一些类似这样的信息：
>    ![image](https://user-images.githubusercontent.com/45255699/99927293-d7d3a380-2d7f-11eb-96db-a31e50903155.png)

第二步：可以看到错误信息，比如
![image](https://user-images.githubusercontent.com/19933500/99928886-10767b80-2d86-11eb-9363-d0dc0ff3db88.png)

**Comment by GvcZhang** [comment]
![image](https://user-images.githubusercontent.com/45255699/99933353-c4333780-2d95-11eb-978c-ec2cfcba60a1.png)

我看这边有错误是没有权限，这块配置可以手动下载然后在aspectd的`pubspec.yaml`中设置吗？具体该如何操作呢？

**Comment by GvcZhang** [comment]
我修改 aspectd 中的 kernel 地址如下，还是不行：
![image](https://user-images.githubusercontent.com/45255699/99940648-8dfeb380-2da7-11eb-8151-0e5dd93de09d.png)

**Comment by GvcZhang** [comment]
@fightcoder 大佬，你好，请教一个问题，关于这篇文章：https://juejin.cn/post/6892371163859976199#heading-15 的几个问题，可否帮忙解惑一下？

1. 如何区分 Widget 是自己创建的呢（没想明白）？
2. `_resolveFlutterClasse`中用到的`_localWidgetLocation `有什么用呢？

主要是第一个问题，感激大佬帮忙。

**Comment by fightcoder** [comment]
> @fightcoder 大佬，你好，请教一个问题，关于这篇文章：https://juejin.cn/post/6892371163859976199#heading-15 的几个问题，可否帮忙解惑一下？
> 
> 1. 如何区分 Widget 是自己创建的呢（没想明白）？
> 2. `_resolveFlutterClasse`中用到的`_localWidgetLocation `有什么用呢？
> 
> 主要是第一个问题，感激大佬帮忙。

coderwangzi@163.com
