### ISSUE TITLE
编译问题好多问题啊，要怎么弄

### ISSUE THREAD

**Issue by just-for-you** [alibaba-flutter/aspectd#65]
壳依赖，sdk源码由于网络原因无法下载，通过手动下载然后源码依赖的形式，无法编译通过

flutter dart  aspect 都是1.22.2
![image](https://user-images.githubusercontent.com/5638270/99952801-31a58f00-2dbb-11eb-824b-5d3ced9807b6.png)

![image](https://user-images.githubusercontent.com/5638270/99952895-5b5eb600-2dbb-11eb-8bca-b8b4db0cb58f.png)

[  +14 ms] [  +12 ms] Done persisting file store
[  +15 ms] [   +6 ms] Target kernel_snapshot failed: Exception: Aspectd unexpected error: ../lib/src/flutter_frontend_server/rebased_package_config.json: Error: Problem in packages configuration file:
Unrecognized string escape
[  +21 ms]            Error: Could not resolve the package 'args' in 'package:args/args.dart'.
[  +13 ms]            Error: Could not resolve the package 'frontend_server' in 'package:frontend_server/frontend_server.dart'.
[  +13 ms]            Error: Could not resolve the package 'kernel' in 'package:kernel/ast.dart'.
[   +4 ms]            Error: Could not resolve the package 'path' in 'package:path/path.dart'.
[   +2 ms]            Error: Could not resolve the package 'vm' in 'package:vm/incremental_compiler.dart'.
[   +6 ms]            Error: Could not resolve the package 'vm' in 'package:vm/target/flutter.dart'.
[  +15 ms]            ../lib/src/flutter_frontend_server/server.dart:10:8: Error: Not found: 'package:args/args.dart'
[  +11 ms]            import 'package:args/args.dart';
[   +4 ms]                   ^
[  +13 ms]            ../lib/src/flutter_frontend_server/server.dart:11:8: Error: Not found: 'package:frontend_server/frontend_server.dart'
[  +10 ms]            import 'package:frontend_server/frontend_server.dart' as frontend
[  +14 ms]                   ^
[   +4 ms]            ../lib/src/flutter_frontend_server/server.dart:19:8: Error: Not found: 'package:kernel/ast.dart'
[   +9 ms]            import 'package:kernel/ast.dart';
[   +8 ms]                   ^
[  +23 ms]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[  +16 ms]            #1      AspectdHook.checkAspectdFlutterFrontendServerSnapshot (package:flutter_tools/src/aspectd.dart:131:9)
[  +64 ms]            <asynchronous suspension>
[   +8 ms]            #2      AspectdHook.isAspectdEnabled (package:flutter_tools/src/aspectd.dart:85:18)
[   +5 ms]            <asynchronous suspension>
[  +16 ms]            #3      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:198:27)
[  +11 ms]            <asynchronous suspension>
[   +3 ms]            #4      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
[   +9 ms]            #5      _rootRunUnary (dart:async/zone.dart:1198:47)
[ +107 ms]            #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[  +18 ms]            #7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[  +29 ms]            #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +3 ms]            #9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[  +10 ms]            #10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +4 ms]            #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +7 ms]            #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[   +3 ms]            #13     Node.computeChanges (package:flutter_tools/src/build_system/build_system.dart)
[   +4 ms]            #14     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +5 ms]            #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[  +20 ms]            #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[  +22 ms]            #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[  +17 ms]            #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[  +22 ms]            #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +9 ms]            #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[  +15 ms]            #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[  +74 ms]            #22     FileStore.diffFileList (package:flutter_tools/src/build_system/file_store.dart)
[  +42 ms]            #23     _rootRunUnary (dart:async/zone.dart:1198:47)
[  +16 ms]            #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +4 ms]            #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +7 ms]            #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +4 ms]            #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +8 ms]            #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +5 ms]            #29     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[   +6 ms]            #30     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +4 ms]            #31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +5 ms]            #32     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[  +12 ms]            #33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +6 ms]            #34     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +4 ms]            #35     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[  +11 ms]            #36     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +7 ms]            #37     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[  +10 ms]            #38     FileStore._hashFile (package:flutter_tools/src/build_system/file_store.dart)
[   +4 ms]            #39     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +6 ms]            #40     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[  +19 ms]            #41     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +7 ms]            #42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +6 ms]            #43     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +7 ms]            #44     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +3 ms]            #45     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[  +10 ms]            #46     _rootRun (dart:async/zone.dart:1190:13)
[   +6 ms]            #47     _CustomZone.run (dart:async/zone.dart:1093:19)
[   +3 ms]            #48     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[   +6 ms]            #49     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[   +3 ms]            #50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[   +2 ms]            #51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[   +5 ms]            #52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[   +6 ms]            #53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[  +21 ms] [  +18 ms] 
[   +5 ms]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[   +4 ms]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:238:7)
[   +3 ms]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[   +3 ms]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +7 ms]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +2 ms]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +2 ms]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +2 ms]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +5 ms]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +5 ms]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[   +5 ms]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[   +4 ms]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[  +12 ms]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +5 ms]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +6 ms]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +7 ms]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +7 ms]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +7 ms]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +4 ms]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[   +7 ms]            #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[   +3 ms]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +8 ms]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +3 ms]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +8 ms]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[  +11 ms]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +6 ms]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +8 ms]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[   +5 ms]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +4 ms]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +4 ms]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +5 ms]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +5 ms]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +4 ms]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +5 ms]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +2 ms]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[   +5 ms]            #35     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[   +7 ms]            #36     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[   +4 ms]            #37     _rootRunBinary (dart:async/zone.dart:1214:47)
[   +4 ms]            #38     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[   +4 ms]            #39     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[   +7 ms]            #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[   +5 ms]            #41     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[   +6 ms]            #42     Future._completeError (dart:async/future_impl.dart:537:5)
[   +3 ms]            #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[   +3 ms]            #44     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart)
[   +6 ms]            #45     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[   +6 ms]            #46     _rootRunBinary (dart:async/zone.dart:1214:47)
[   +4 ms]            #47     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[   +2 ms]            #48     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[   +6 ms]            #49     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[   +2 ms]            #50     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[   +4 ms]            #51     Future._completeError (dart:async/future_impl.dart:537:5)
[   +5 ms]            #52     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[   +3 ms]            #53     AspectdHook.isAspectdEnabled (package:flutter_tools/src/aspectd.dart)
[   +6 ms]            #54     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[   +5 ms]            #55     _rootRunBinary (dart:async/zone.dart:1214:47)
[   +4 ms]            #56     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[   +3 ms]            #57     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[  +12 ms]            #58     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[   +7 ms]            #59     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[   +3 ms]            #60     Future._completeError (dart:async/future_impl.dart:537:5)
[   +6 ms]            #61     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[   +6 ms]            #62     AspectdHook.checkAspectdFlutterFrontendServerSnapshot (package:flutter_tools/src/aspectd.dart)
[  +12 ms]            #63     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +4 ms]            #64     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +4 ms]            #65     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +6 ms]            #66     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +6 ms]            #67     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +5 ms]            #68     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +5 ms]            #69     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +5 ms]            #70     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[   +5 ms]            #71     _run (package:flutter_tools/src/base/error_handling_io.dart)
[   +8 ms]            #72     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +5 ms]            #73     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +4 ms]            #74     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +9 ms]            #75     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +4 ms]            #76     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +9 ms]            #77     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +3 ms]            #78     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[   +7 ms]            #79     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +8 ms]            #80     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +6 ms]            #81     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +3 ms]            #82     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +3 ms]            #83     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +3 ms]            #84     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +3 ms]            #85     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[   +6 ms]            #86     _rootRun (dart:async/zone.dart:1190:13)
[   +4 ms]            #87     _CustomZone.run (dart:async/zone.dart:1093:19)
[   +3 ms]            #88     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[   +6 ms]            #89     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[   +5 ms]            #90     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[   +2 ms]            #91     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[   +3 ms]            #92     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[   +6 ms]            #93     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[   +5 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[   +5 ms] Script 'D:\programflies\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904
[   +4 ms] * What went wrong:
[   +3 ms] Execution failed for task ':app:compileFlutterBuildDebug'.
[   +3 ms] > Process 'command 'D:\programflies\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +4 ms] * Try:
[   +7 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[  +13 ms] * Get more help at https://help.gradle.org
[   +7 ms] BUILD FAILED in 38s
[   +5 ms] [  +57 ms] "flutter assemble" took 14,670ms.
[   +5 ms] [  +33 ms] ensureAnalyticsSent: 0ms
[   +4 ms] [   +3 ms] Running shutdown hooks
[   +5 ms] [        ] Shutdown hooks complete
[   +4 ms] [   +1 ms] exiting with code 1
[   +4 ms] > Task :app:compileFlutterBuildDebug FAILED
[   +5 ms] 1 actionable task: 1 executed
[  +22 ms] Running Gradle task 'assembleDebug'... (completed in 40.2s)
[  +16 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 41,930ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +310 ms] ensureAnalyticsSent: 252ms
[   +4 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[   +9 ms] Shutdown hooks complete
[   +3 ms] exiting with code 1

**Comment by kangwang1988** [comment]
See https://github.com/alibaba-flutter/aspectd/issues/67
