### ISSUE TITLE
如何搞懂 AspectD 的原理？

### ISSUE THREAD

**Issue by GvcZhang** [alibaba-flutter/aspectd#66]
我想深入了解 AspectD，
1. 我应该从哪些方面来入手呢？
2. 比如需要哪些相关的知识？dill 是什么、transform 是什么
3. 需要研究 Dart SDK 源码吗？
4. 如何阅读和调试源码呢？

有没有人愿意一起研究的，我可以建一个群，一起交流。

**Comment by kangwang1988** [comment]
See README
https://github.com/alibaba-flutter/aspectd

If you know how to debug flutter tools, see https://github.com/flutter/flutter/wiki/The-flutter-tool

Also see
https://juejin.cn/post/6844903873644068872

**Comment by GvcZhang** [comment]
http://gityuan.com/2019/09/01/flutter_tool/

**Comment by GvcZhang** [comment]
@fightcoder 大佬，我现在看你的那篇文章陷入了无限的知识漏洞中，我是一个人研究的，现在处境很难，比如你说的 Transformer、dill，这一块有没有资料介绍一下，无比感谢！

**Comment by fightcoder** [comment]
> @fightcoder 大佬，我现在看你的那篇文章陷入了无限的知识漏洞中，我是一个人研究的，现在处境很难，比如你说的 Transformer、dill，这一块有没有资料介绍一下，无比感谢！

你好，应该没有你需要详细文字资料，只有代码，后面会出讲解+实际应用案例，可以关注一下。

**Comment by GvcZhang** [comment]
> > @fightcoder 大佬，我现在看你的那篇文章陷入了无限的知识漏洞中，我是一个人研究的，现在处境很难，比如你说的 Transformer、dill，这一块有没有资料介绍一下，无比感谢！
> 
> 你好，应该没有你需要详细文字资料，只有代码，后面会出讲解+实际应用案例，可以关注一下。

大佬，那有没有入口点呢？比如代码的话，从哪里看起呢？

**Comment by GvcZhang** [comment]
@kangwang1988 I want to build dart file to a dill file, and I follow this step:
![image](https://user-images.githubusercontent.com/45255699/101501857-35d0cf80-39ab-11eb-8e73-1999fe1a84f7.png)
When i do it  on my pc, it tells me:
![image](https://user-images.githubusercontent.com/45255699/101501984-5e58c980-39ab-11eb-8b95-bb39c3e84e21.png)

How can i build dart file to dill file?

**Comment by GvcZhang** [comment]
@fightcoder 大佬，我现在有很多不明白的地方，可否留一个联系方式，愿意有偿咨询。

**Comment by fightcoder** [comment]
> @fightcoder 大佬，我现在有很多不明白的地方，可否留一个联系方式，愿意有偿咨询。
不用这么客气，最近很多事情，缓两天吧，你可以先把aspectd的案例跑起来多尝试下~
