### ISSUE TITLE
Windows Support Issue

### ISSUE THREAD

**Issue by kangwang1988** [alibaba-flutter/aspectd#67]
As I'm using Mac for development and the aop implementation doesn't depend on the host OS. I think the principle should also works on windows.

However, now, I receive several issues about windows, if you met problem on windows or want to fix it on windows, you're welcome to do that.

**Comment by fightcoder** [comment]
#68

**Comment by fightcoder** [comment]
#68 兼容windows上的使用。

**Comment by kangwang1988** [comment]
Close this issue as I think the patch apply is working with: https://github.com/alibaba-flutter/aspectd/commit/ba7003e1f9e113a5b75b42be276ac64f58ba99f9

And the workflow works after https://github.com/alibaba-flutter/aspectd/commit/71e0504f24c68e5a0216b0599b8b6968ca213650 is merged.
