### ISSUE TITLE
dartSha为什么不从/flutter/bin/cache/dart-sdk/revision文件中获取？

### ISSUE THREAD

**Issue by galaxybruce** [alibaba-flutter/aspectd#7]
aspectd.dart文件中getExpectedDartSha()方法获取dartSha，必须先下载DEPS文件（http://raw.githubusercontent.com/flutter/engine/$engineVersion/DEPS），这个文件必须开启vpn才能下载，有时候还很慢。为什么不直接从flutter/bin/cache/dart-sdk/revision文件中读取呢？
像这样：
`  
static Future<String> getExpectedDartSha() async {
    final File dartShaFile = fs.file(
        fs.path.join(Cache.flutterRoot, 'bin', 'cache', 'dart-sdk', 'revision'));
    final String dartSha = dartShaFile.readAsStringSync().trim();
    print('===dartSha: $dartSha');
    return Future<String>.sync(() => dartSha);
}
`

**Comment by kangwang1988** [comment]
Nice shot.

**Comment by galaxybruce** [comment]
> Nice shot.

这段代码测试过，结果也是正确的

**Comment by kangwang1988** [comment]
@galaxybruce 
Thanks
I've refactor the related logic (https://github.com/alibaba-flutter/aspectd/commit/f1cfba350cd862e282a0aba86b6b20430d796455) and it works fine.

**Comment by kangwang1988** [comment]
Close this issue as merged.
