### ISSUE TITLE
aspectd 使用 AS 打开有很多错误

### ISSUE THREAD

**Issue by GvcZhang** [alibaba-flutter/aspectd#76]
![image](https://user-images.githubusercontent.com/45255699/101599948-999fda80-3a35-11eb-8e2e-1649fc6df7bd.png)

**Comment by kangwang1988** [comment]
不要理他，没关系的，他的依赖关系不是通过pubspec.yaml和.lock以及.packages描述的
有大量的sdk的依赖是透过.dart_tool/package_config.json的，分析不出来不影响啥。
