### ISSUE TITLE
源码中的 visitChildren 和 transformChildren 是什么意思？

### ISSUE THREAD

**Issue by IamKing** [alibaba-flutter/aspectd#77]
![image](https://user-images.githubusercontent.com/2776376/101623361-4c326600-3a53-11eb-9f45-e274f69d805c.png)
kernal中没找到对应的注释说明

**Comment by IamKing** [comment]
再补充一个，aspectD 如何进行 debug

**Comment by kangwang1988** [comment]
> ![image](https://user-images.githubusercontent.com/2776376/101623361-4c326600-3a53-11eb-9f45-e274f69d805c.png)
> kernal中没找到对应的注释说明

AST递归遍历

**Comment by kangwang1988** [comment]
> 再补充一个，aspectD 如何进行 debug

首先你需要搞清楚flutter_tools工具链中dill如何生成的

这个过程中会涉及到frontend_server.dart.snapshot的调用

这个snapshot本身是可以自行重建或者调试的，

   final List<String> commands = <String>[
+        globals.artifacts.getArtifactPath(Artifact.engineDartBinary),
+        '--deterministic',
+        '--packages=$rebasedFrontendServerPackageConfigJsonFile',
+        '--snapshot=$aspectdFlutterFrontendServerSnapshot',
+        '--snapshot-kind=kernel',
+        '${flutterFrontendServerDirectory.absolute.path}/starter.dart'
+      ];

你把aspectd中的start.dart这部分，当做一个正常的dart command line app, 在as打开就可以去执行对应逻辑了。构建中会有transformer的调用和实现，就可以实现调试功能了。

**Comment by IamKing** [comment]
感谢！
