### ISSUE TITLE
修改 aspectd 后，运行工程总是走老的逻辑

### ISSUE THREAD

**Issue by GvcZhang** [alibaba-flutter/aspectd#84]
这里其实包括两个问题：
1. 如何将自定义的 transform 添加到 aspectd 中？
2. 我修改了 aspectd 中的代码后，并没有效果，aspectd 总是走老的逻辑，即使我注销了某段代码，运行的时候还是会走，如何让修改后的内容生效呢？

辛苦大佬，帮忙看一下这两个问题

**Comment by kangwang1988** [comment]
自己调试看看
