### ISSUE TITLE
请教如何进行 aspectd 的调试

### ISSUE THREAD

**Issue by GvcZhang** [alibaba-flutter/aspectd#85]
我目前按照 [Flutter Tools](https://github.com/flutter/flutter/wiki/The-flutter-tool#debugging-the-flutter-command-line-tool) 中的方法进行了配置，然后按照 https://github.com/alibaba-flutter/aspectd/issues/45 的调试方式进行测试，同时删除了 example 工程中的 build、flutter_build 目录以及 aspectd_impl 工程的 flutter_build 目录，测试结果是可以正常编译并且运行项目，但是我在 aspectd.dart 中`runBuildDillCommand`方法中的断点还是无法执行到，请教是哪里的操作不对吗？

![image](https://user-images.githubusercontent.com/45255699/102738309-a94be700-4384-11eb-99e6-8747a4c38ab0.png)

我看日志输出，应该是走到 kernel_snapshot 的逻辑，为什么断点没有进入呢：
![image](https://user-images.githubusercontent.com/45255699/102747533-69442e80-439b-11eb-846a-05c7ebe7a56f.png)

**Comment by GvcZhang** [comment]
@kangwang1988 还是没有搞明白这个问题，可否提点一下~

**Comment by zhuangtao97** [comment]
> @kangwang1988 还是没有搞明白这个问题，可否提点一下~


> @kangwang1988 还是没有搞明白这个问题，可否提点一下~

搞定了吗，我也是无法进入断点，按照#45那样做也不行
