### ISSUE TITLE
修改tool/starter.dart，aspectd.dart.snapshot也正确生成，为什么运行却没效果？

### ISSUE THREAD

**Issue by galaxybruce** [alibaba-flutter/aspectd#9]
@kangwang1988 
这是一个和aspectd本身没关系的问题。
我只是想在这项目的基础上做一些定制，我在starter.dart文件里打印了一些日志，aspected.dart.snaphost也正确生成了，但是实际编译的时候却没有打印日志。另外，aspectd.dart文件中打印的语句编译时是能正常输出的。
![image](https://user-images.githubusercontent.com/2462686/63904424-7ff6a180-ca43-11e9-8208-305c0f9ba434.png)

**Comment by galaxybruce** [comment]
> @kangwang1988
> 这是一个和aspectd本身没关系的问题。
> 我只是想在这项目的基础上做一些定制，我在starter.dart文件里打印了一些日志，aspected.dart.snaphost也正确生成了，但是实际编译的时候却没有打印日志。另外，aspectd.dart文件中打印的语句编译时是能正常输出的。
> ![image](https://user-images.githubusercontent.com/2462686/63904424-7ff6a180-ca43-11e9-8208-305c0f9ba434.png)

我知道了，ProcessManager.run中执行的命令代码中的输出托管在了result中，通过result.stdout.toString()可以输出。

**Comment by fightcoder** [comment]
你好

> > @kangwang1988
> > 这是一个和aspectd本身没关系的问题。
> > 我只是想在这项目的基础上做一些定制，我在starter.dart文件里打印了一些日志，aspected.dart.snaphost也正确生成了，但是实际编译的时候却没有打印日志。另外，aspectd.dart文件中打印的语句编译时是能正常输出的。
> > ![image](https://user-images.githubusercontent.com/2462686/63904424-7ff6a180-ca43-11e9-8208-305c0f9ba434.png)
> 
> 我知道了，ProcessManager.run中执行的命令代码中的输出托管在了result中，通过result.stdout.toString()可以输出。

你好，请教下这个咋输出？print好像没看到日志，在哪里看呢，
