### ISSUE TITLE
配置协助～

### ISSUE THREAD

**Issue by ConnyYue** [alibaba-flutter/aspectd#90]
我把库下载到了本地 但是跑不起来

![image](https://user-images.githubusercontent.com/16607263/103861241-1044fc00-50f8-11eb-81a4-27a9c6da0552.png)

想问一下pubspec.yaml里面的以来地址可以改成 https://github.com/alibaba-flutter/sdk.git 吗

不知道为啥 不管用https还是ssh都好慢
flutter pub get  一直卡住.......
有没有什么好办法

![image](https://user-images.githubusercontent.com/16607263/103880161-b5210280-5113-11eb-8ffb-cb9ba089cb55.png)

**Comment by ameryzhu** [comment]
@ConnyYue 

I folked a mirror through gitee,it's pretty fast, you can use mine.

dependency_overrides:
  kernel:
    git:
#      url: https://github.com/alibaba-flutter/sdk.git
      ### mirrors in china
      url: https://gitee.com/crazydroid2014/sdk.git
      ref: stable/v1.22.4
      path: pkg/kernel

**Comment by ConnyYue** [comment]
> @ConnyYue
> 
> I folked a mirror through gitee,it's pretty fast, you can use mine.
> 
> dependency_overrides:
> kernel:
> git:
> ### url: https://github.com/alibaba-flutter/sdk.git
> ### mirrors in china
> url: https://gitee.com/crazydroid2014/sdk.git
> ref: stable/v1.22.4
> path: pkg/kernel

Thanks. I will try it.

**Comment by ConnyYue** [comment]
> @ConnyYue
> 
> I folked a mirror through gitee,it's pretty fast, you can use mine.
> 
> dependency_overrides:
> kernel:
> git:
> ### url: https://github.com/alibaba-flutter/sdk.git
> ### mirrors in china
> url: https://gitee.com/crazydroid2014/sdk.git
> ref: stable/v1.22.4
> path: pkg/kernel

Its helpful hints.   
Thanks.

**Comment by kangwang1988** [comment]
Network issue, thanks for @ameryzhu  's mirror.
