### ISSUE TITLE
flutter_frontend_server.snapshot升级问题

### ISSUE THREAD

**Issue by 1004145468** [alibaba-flutter/aspectd#92]
参考UPGRADE.md发现engine/src/flutter/flutter_frontend_server/.dart_tool目录并没有生成，无法获取package_config.json文件

**Comment by kangwang1988** [comment]
![image](https://user-images.githubusercontent.com/817851/104866799-688ec000-597a-11eb-9269-5194d6d8b3a6.png)

gclient sync成功后，自然会有的，stable我都是看过ok的，这张图是master@609036f2bf7cae17a0b88c21fb3bdaff7159b713

也是没问题的。

**Comment by kangwang1988** [comment]
{
  "configVersion": 2,
  "packages": [
    {
      "name": "flutter_frontend_server",
      "rootUri": "../",
      "packageUri": "lib",
      "languageVersion": "2.2"
    },
    {
      "name": "_fe_analyzer_shared",
      "rootUri": "../../../third_party/dart/pkg/_fe_analyzer_shared",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "_js_interop_checks",
      "rootUri": "../../../third_party/dart/pkg/_js_interop_checks",
      "packageUri": "lib",
      "languageVersion": "2.7"
    },
    {
      "name": "analysis_server",
      "rootUri": "../../../third_party/dart/pkg/analysis_server",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "analysis_server_client",
      "rootUri": "../../../third_party/dart/pkg/analysis_server_client",
      "packageUri": "lib",
      "languageVersion": "2.8"
    },
    {
      "name": "analyzer",
      "rootUri": "../../../third_party/dart/pkg/analyzer",
      "packageUri": "lib",
      "languageVersion": "2.9"
    },
    {
      "name": "analyzer_cli",
      "rootUri": "../../../third_party/dart/pkg/analyzer_cli",
      "packageUri": "lib",
      "languageVersion": "2.7"
    },
    {
      "name": "analyzer_plugin",
      "rootUri": "../../../third_party/dart/pkg/analyzer_plugin",
      "packageUri": "lib",
      "languageVersion": "2.9"
    },
    {
      "name": "analyzer_utilities",
      "rootUri": "../../../third_party/dart/pkg/analyzer_utilities",
      "packageUri": "lib",
      "languageVersion": "2.1"
    },
    {
      "name": "async_helper",
      "rootUri": "../../../third_party/dart/pkg/async_helper",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "build_integration",
      "rootUri": "../../../third_party/dart/pkg/build_integration",
      "packageUri": "lib",
      "languageVersion": "2.1"
    },
    {
      "name": "compiler",
      "rootUri": "../../../third_party/dart/pkg/compiler",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "dart2js_tools",
      "rootUri": "../../../third_party/dart/pkg/dart2js_tools",
      "packageUri": "lib",
      "languageVersion": "2.3"
    },
    {
      "name": "dart2native",
      "rootUri": "../../../third_party/dart/pkg/dart2native",
      "packageUri": "lib",
      "languageVersion": "2.7"
    },
    {
      "name": "dart_internal",
      "rootUri": "../../../third_party/dart/pkg/dart_internal",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "dartdev",
      "rootUri": "../../../third_party/dart/pkg/dartdev",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "dds",
      "rootUri": "../../../third_party/dart/pkg/dds",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "dev_compiler",
      "rootUri": "../../../third_party/dart/pkg/dev_compiler",
      "packageUri": "lib",
      "languageVersion": "2.3"
    },
    {
      "name": "diagnostic",
      "rootUri": "../../../third_party/dart/pkg/diagnostic",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "expect",
      "rootUri": "../../../third_party/dart/pkg/expect",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "front_end",
      "rootUri": "../../../third_party/dart/pkg/front_end",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "frontend_server",
      "rootUri": "../../../third_party/dart/pkg/frontend_server",
      "packageUri": "lib",
      "languageVersion": "2.7"
    },
    {
      "name": "js",
      "rootUri": "../../../third_party/dart/pkg/js",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "js_ast",
      "rootUri": "../../../third_party/dart/pkg/js_ast",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "kernel",
      "rootUri": "../../../third_party/dart/pkg/kernel",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "meta",
      "rootUri": "../../../third_party/dart/pkg/meta",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "modular_test",
      "rootUri": "../../../third_party/dart/pkg/modular_test",
      "packageUri": "lib",
      "languageVersion": "2.2"
    },
    {
      "name": "native_stack_traces",
      "rootUri": "../../../third_party/dart/pkg/native_stack_traces",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "nnbd_migration",
      "rootUri": "../../../third_party/dart/pkg/nnbd_migration",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "smith",
      "rootUri": "../../../third_party/dart/pkg/smith",
      "packageUri": "lib",
      "languageVersion": "2.3"
    },
    {
      "name": "sourcemap_testing",
      "rootUri": "../../../third_party/dart/pkg/sourcemap_testing",
      "packageUri": "lib",
      "languageVersion": "2.1"
    },
    {
      "name": "status_file",
      "rootUri": "../../../third_party/dart/pkg/status_file",
      "packageUri": "lib",
      "languageVersion": "2.3"
    },
    {
      "name": "telemetry",
      "rootUri": "../../../third_party/dart/pkg/telemetry",
      "packageUri": "lib",
      "languageVersion": "1.0"
    },
    {
      "name": "test_runner",
      "rootUri": "../../../third_party/dart/pkg/test_runner",
      "packageUri": "lib",
      "languageVersion": "2.3"
    },
    {
      "name": "testing",
      "rootUri": "../../../third_party/dart/pkg/testing",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "vm",
      "rootUri": "../../../third_party/dart/pkg/vm",
      "packageUri": "lib",
      "languageVersion": "2.7"
    },
    {
      "name": "vm_service",
      "rootUri": "../../../third_party/dart/pkg/vm_service",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "vm_snapshot_analysis",
      "rootUri": "../../../third_party/dart/pkg/vm_snapshot_analysis",
      "packageUri": "lib",
      "languageVersion": "2.8"
    },
    {
      "name": "wasm",
      "rootUri": "../../../third_party/dart/pkg/wasm",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "observatory",
      "rootUri": "../../../third_party/dart/runtime/observatory",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "js_runtime",
      "rootUri": "../../../third_party/dart/sdk/lib/_internal/js_runtime",
      "packageUri": "lib",
      "languageVersion": "2.2"
    },
    {
      "name": "sdk_library_metadata",
      "rootUri": "../../../third_party/dart/sdk/lib/_internal/sdk_library_metadata",
      "packageUri": "lib",
      "languageVersion": "2.11"
    },
    {
      "name": "args",
      "rootUri": "../../../third_party/dart/third_party/pkg/args",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "async",
      "rootUri": "../../../third_party/dart/third_party/pkg/async",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "bazel_worker",
      "rootUri": "../../../third_party/dart/third_party/pkg/bazel_worker",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "boolean_selector",
      "rootUri": "../../../third_party/dart/third_party/pkg/boolean_selector",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "charcode",
      "rootUri": "../../../third_party/dart/third_party/pkg/charcode",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "cli_util",
      "rootUri": "../../../third_party/dart/third_party/pkg/cli_util",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "collection",
      "rootUri": "../../../third_party/dart/third_party/pkg/collection",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "convert",
      "rootUri": "../../../third_party/dart/third_party/pkg/convert",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "crypto",
      "rootUri": "../../../third_party/dart/third_party/pkg/crypto",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "csslib",
      "rootUri": "../../../third_party/dart/third_party/pkg/csslib",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "dart2js_info",
      "rootUri": "../../../third_party/dart/third_party/pkg/dart2js_info",
      "packageUri": "lib",
      "languageVersion": "2.3"
    },
    {
      "name": "dartdoc",
      "rootUri": "../../../third_party/dart/third_party/pkg/dartdoc",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "ffi",
      "rootUri": "../../../third_party/dart/third_party/pkg/ffi",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "fixnum",
      "rootUri": "../../../third_party/dart/third_party/pkg/fixnum",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "glob",
      "rootUri": "../../../third_party/dart/third_party/pkg/glob",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "html",
      "rootUri": "../../../third_party/dart/third_party/pkg/html",
      "packageUri": "lib",
      "languageVersion": "2.8"
    },
    {
      "name": "http",
      "rootUri": "../../../third_party/dart/third_party/pkg/http",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "http_multi_server",
      "rootUri": "../../../third_party/dart/third_party/pkg/http_multi_server",
      "packageUri": "lib",
      "languageVersion": "2.1"
    },
    {
      "name": "http_parser",
      "rootUri": "../../../third_party/dart/third_party/pkg/http_parser",
      "packageUri": "lib",
      "languageVersion": "2.11"
    },
    {
      "name": "http_retry",
      "rootUri": "../../../third_party/dart/third_party/pkg/http_retry",
      "packageUri": "lib",
      "languageVersion": "1.24"
    },
    {
      "name": "http_throttle",
      "rootUri": "../../../third_party/dart/third_party/pkg/http_throttle",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "intl",
      "rootUri": "../../../third_party/dart/third_party/pkg/intl",
      "packageUri": "lib",
      "languageVersion": "2.11"
    },
    {
      "name": "json_rpc_2",
      "rootUri": "../../../third_party/dart/third_party/pkg/json_rpc_2",
      "packageUri": "lib",
      "languageVersion": "2.2"
    },
    {
      "name": "linter",
      "rootUri": "../../../third_party/dart/third_party/pkg/linter",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "logging",
      "rootUri": "../../../third_party/dart/third_party/pkg/logging",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "markdown",
      "rootUri": "../../../third_party/dart/third_party/pkg/markdown",
      "packageUri": "lib",
      "languageVersion": "2.6"
    },
    {
      "name": "matcher",
      "rootUri": "../../../third_party/dart/third_party/pkg/matcher",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "mime",
      "rootUri": "../../../third_party/dart/third_party/pkg/mime",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "mockito",
      "rootUri": "../../../third_party/dart/third_party/pkg/mockito",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "mustache",
      "rootUri": "../../../third_party/dart/third_party/pkg/mustache",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "oauth2",
      "rootUri": "../../../third_party/dart/third_party/pkg/oauth2",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "path",
      "rootUri": "../../../third_party/dart/third_party/pkg/path",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "pedantic",
      "rootUri": "../../../third_party/dart/third_party/pkg/pedantic",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "pool",
      "rootUri": "../../../third_party/dart/third_party/pkg/pool",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "protobuf",
      "rootUri": "../../../third_party/dart/third_party/pkg/protobuf/protobuf",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "pub",
      "rootUri": "../../../third_party/dart/third_party/pkg/pub",
      "packageUri": "lib",
      "languageVersion": "2.11"
    },
    {
      "name": "pub_semver",
      "rootUri": "../../../third_party/dart/third_party/pkg/pub_semver",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "resource",
      "rootUri": "../../../third_party/dart/third_party/pkg/resource",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "shelf",
      "rootUri": "../../../third_party/dart/third_party/pkg/shelf",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "shelf_packages_handler",
      "rootUri": "../../../third_party/dart/third_party/pkg/shelf_packages_handler",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "shelf_proxy",
      "rootUri": "../../../third_party/dart/third_party/pkg/shelf_proxy",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "shelf_static",
      "rootUri": "../../../third_party/dart/third_party/pkg/shelf_static",
      "packageUri": "lib",
      "languageVersion": "2.3"
    },
    {
      "name": "shelf_web_socket",
      "rootUri": "../../../third_party/dart/third_party/pkg/shelf_web_socket",
      "packageUri": "lib",
      "languageVersion": "2.0"
    },
    {
      "name": "source_map_stack_trace",
      "rootUri": "../../../third_party/dart/third_party/pkg/source_map_stack_trace",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "source_maps",
      "rootUri": "../../../third_party/dart/third_party/pkg/source_maps",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "source_span",
      "rootUri": "../../../third_party/dart/third_party/pkg/source_span",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "sse",
      "rootUri": "../../../third_party/dart/third_party/pkg/sse",
      "packageUri": "lib",
      "languageVersion": "2.2"
    },
    {
      "name": "stack_trace",
      "rootUri": "../../../third_party/dart/third_party/pkg/stack_trace",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "stagehand",
      "rootUri": "../../../third_party/dart/third_party/pkg/stagehand",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "stream_channel",
      "rootUri": "../../../third_party/dart/third_party/pkg/stream_channel",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "string_scanner",
      "rootUri": "../../../third_party/dart/third_party/pkg/string_scanner",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "term_glyph",
      "rootUri": "../../../third_party/dart/third_party/pkg/term_glyph",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "test",
      "rootUri": "../../../third_party/dart/third_party/pkg/test/pkgs/test",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "test_api",
      "rootUri": "../../../third_party/dart/third_party/pkg/test/pkgs/test_api",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "test_core",
      "rootUri": "../../../third_party/dart/third_party/pkg/test/pkgs/test_core",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "test_reflective_loader",
      "rootUri": "../../../third_party/dart/third_party/pkg/test_reflective_loader",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "typed_data",
      "rootUri": "../../../third_party/dart/third_party/pkg/typed_data",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "usage",
      "rootUri": "../../../third_party/dart/third_party/pkg/usage",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "watcher",
      "rootUri": "../../../third_party/dart/third_party/pkg/watcher",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "web_socket_channel",
      "rootUri": "../../../third_party/dart/third_party/pkg/web_socket_channel",
      "packageUri": "lib",
      "languageVersion": "2.10"
    },
    {
      "name": "yaml",
      "rootUri": "../../../third_party/dart/third_party/pkg/yaml",
      "packageUri": "lib",
      "languageVersion": "2.12"
    },
    {
      "name": "dart_style",
      "rootUri": "../../../third_party/dart/third_party/pkg_tested/dart_style",
      "packageUri": "lib",
      "languageVersion": "2.9"
    },
    {
      "name": "package_config",
      "rootUri": "../../../third_party/dart/third_party/pkg_tested/package_config",
      "packageUri": "lib",
      "languageVersion": "2.7"
    }
  ]
}
